redoing backstop job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,16 +41,45 @@ orbs:
 
 jobs:
   backstop:
-      docker:
-          - image: backstopjs/backstopjs:3.9.5
-      working_directory: ~/example_drops_8_composer
-      steps:
-          - playground/setbashenv
-          - run: cd backstop && ./run-backstop.sh
-          - store_artifacts:
-              path: /tmp/artifacts
-              destination: artifact
-          - run: ./backstop/report-backstop.sh
+    docker:
+    - image: backstopjs/backstopjs:3.9.5
+    steps:
+    - playground/setbashenv
+    - run: backstop reference --config=backstop/backstop-config.js
+    - run: backstop test --config=backstop/backstop-config.js || touch backstop_failed.txt
+    - store_artifacts:
+        path: backstop_data
+
+    - run:
+        name: Report
+        command: |
+              CIRCLE_ARTIFACTS_URL=${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/root/project
+              IMAGE=$(find -- backstop_data/bitmaps_test -type f -name "*.png" | head -n 1)
+              REPORT_URL=${CIRCLE_ARTIFACTS_URL}/backstop_data/html_report/index.html
+              BODY="### Visual regression report:\\n\\n[![Visual report](${CIRCLE_ARTIFACTS_URL}/${IMAGE})]($REPORT_URL)"
+              {
+                GITHUB_URL="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1}/comments?access_token=${GITHUB_TOKEN}"
+                curl -d '{ "body": "'"${BODY}"'" }' -X POST "${GITHUB_URL}"
+              } &> /dev/null
+
+
+    - run:
+        name: Report
+        command: |
+          if [ -f "backstop_failed.txt" ] ; then
+            echo "Backstop report failed."
+            exit 1
+          fi
+
+
+
+
+
+
+
+
+
+
 
   behavioral:
       docker:
