param and head error suppression

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,19 +41,24 @@ orbs:
 
 jobs:
   backstop:
+    parameters:
+      path_to_backstop_config:
+        type: string
+        default: "backstop/backstop-config.js"
     docker:
     - image: backstopjs/backstopjs:3.9.5
     steps:
     - playground/setbashenv
-    - run: backstop reference --config=backstop/backstop-config.js
-    - run: backstop test --config=backstop/backstop-config.js || touch backstop_failed.txt
+    - run: backstop reference --config=<<parameters.path_to_backstop_config>>
+    - run: backstop test --config=<<parameters.path_to_backstop_config>> || touch backstop_failed.txt
     - store_artifacts:
         path: backstop_data
     - run:
         name: Report
         command: |
               CIRCLE_ARTIFACTS_URL=${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/root/project
-              IMAGE=$(find -- backstop_data/bitmaps_test -type f -name "*.png" | head -n 1)
+              IMAGE=$(find -- backstop_data/bitmaps_test -type f -name "*.png" | head -n 1) || echo "suppressing a 141 error from head. TODO, something better"
+              echo $IMAGE
               REPORT_URL=${CIRCLE_ARTIFACTS_URL}/backstop_data/html_report/index.html
               BODY="### Visual regression report:\\n\\n[![Visual report](${CIRCLE_ARTIFACTS_URL}/${IMAGE})]($REPORT_URL)"
               {
@@ -68,7 +73,6 @@ jobs:
             echo "Backstop report failed."
             exit 1
           fi
-
 
   behavioral:
       docker:
